name: Merged & PR CI
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/spray
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create file with current datetime as name
        run: |
          touch "$(date +%Y-%m-%dT%H:%M:%S.%6N).txt"



      - name: Commit & Push changes
        uses: Andro999b/push@patch-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          message: >
            "chore: format"
